### ISSUE TITLE
Webhoook property not working for signing type

### ISSUE THREAD

**Issue by nealoke** [ilovepdf/ilovepdf-nodejs#15]
The `webhook` property that is mentioned in the documentation is not working and also throwing a TS error as it is not in the types. 

```ts
const result = await task.process({
	uuid_visible: true,
	brand_logo: brandLogo.serverFilename,
	brand_name: company.name,
	language: 'nl',
	signer_reminder_days_cycle: 3,
	certified: true,
	webhook: 'https://webhook.site/aa72d508-d513-4565-8873-615a8f659bd0',
});
```

### Documentation
![image](https://github.com/ilovepdf/ilovepdf-nodejs/assets/17417414/91d3dddf-8922-4076-9e76-5718c6cfe2dd)

### TS error

> Argument of type '{ uuid_visible: true; brand_logo: string; brand_name: string; language: "nl"; custom_string: string; signer_reminder_days_cycle: number; certified: true; webhook: string; }' is not assignable to parameter of type 'SignProcessParams'.
>   Object literal may only specify known properties, and 'webhook' does not exist in type 'SignProcessParams'.ts(2345)

**Comment by nealoke** [comment]
Also `expiration_days` mentioned in the [Create signature request](https://developer.ilovepdf.com/docs/api-reference#create-signature) endpoint is not in the types... It is getting a bit frustrating to work with this library if the types or out of date and blocking development for us :(

**Comment by guillem-pdf** [comment]
Hi @nealoke ,
Sorry for the incovenience. The library was updated with the corresponding types.

For the future, this kind of problems don't block TypeScript, you can bypass these errors using the type casting system or adding new custom types for your project.

Again, sorry for the incovenience and we will check the parameters in order to provide you a better experience.

**Comment by nealoke** [comment]
@guillem-pdf I know this does not prevent it working but in this issue the missing type is the secondary problem. 

The main issue is that the webhook is simply not working, the process still takes until 1-2 seconds and doesn't call the webhook provided at all...

**Comment by guillem-pdf** [comment]
Hi @nealoke ,

I tried using https://webhook.site/ service and it all seems to be working OK, sometimes it can take up to a minute to receive the webhook.

If you need, we can do a video call so I can understand what the issue is. 

Please fill your contact details [here](https://developer.ilovepdf.com/contact) and ask an appointment with me. Our support team will schedule a call ASAP.

Kind regards,

Guillem.

**Comment by nealoke** [comment]
@guillem-pdf

Webhooks are being called but only when they are added via the https://developer.ilovepdf.com/user/webhooks area, not when they are added as shown in my code snippet 

```js
const result = await task.process({
	uuid_visible: true,
	brand_logo: brandLogo.serverFilename,
	brand_name: company.name,
	language: 'nl',
	signer_reminder_days_cycle: 3,
	certified: true,
	webhook: 'https://webhook.site/aa72d508-d513-4565-8873-615a8f659bd0', // <--- Not called when it is not in the user/webhooks area
});
```

**Comment by nealoke** [comment]
@guillem-pdf any update on this? It is currently blocking deploying our SaaS product...

**Comment by diego-ilovepdf** [comment]
Hi @nealoke !

Sorry for the incovenience, @guillem-pdf is not currently available.

For security reasons, you must add all the webhooks in your user webhooks area. Why is this blocking you?

Diego.

**Comment by nealoke** [comment]
Thanks for the answer. We want dynamic urls here because we need to identify what tenant and project the document that was signed belongs to. There is to my knowledge no other way of passing metadata along which is quite unhandy. Do you have a potential solution for this?

**Comment by maztch** [comment]
You can set custom_int and custom_string properties, then you will be able to filter using it on task list endpoint too.

**Comment by nealoke** [comment]
@maztch @diego-ilovepdf 

So this would mean that we would need to ping the endpoint and figure out what signature corresponds to what ilovepdf job in order to do this? Can't we allow a whitelist of webhook url like `thisdomain.com/ilovepdf/*`?

**Comment by maztch** [comment]
Actually the webhook param (if not null or empty), only sends the job to background, and you need to set the webhook on the user dashboard. This feature needs to be updated on documentation. And has changed in order to allow multiple webhooks on each task, and (also) to prevent malicious usage of webhooks.
If you set your custom_int, you will get it on the webhoo, andt hen you can act on your side.
Using the dashboard you can: set multiple webhooks for each action, set webhooks for specific states, and manage it on your side based on your needs.
And, in addition, using custom_int and.custom_string, you have indexed fields in order to filter tasks (it's a feature, just in case you need to list it, for better history listing).

**Comment by nealoke** [comment]
I'm a bit sad that you need to add webhooks in the dashboard and then only can you use them when defining the process, I'm not sure why this would be more secure really. Either way, we decided to approach it differently by creating a separate table where we will keep the id of the process/signature and the id of the tenant/project in a separate database table. To me having custom_string and custom_int is a bit annoying as a work around and unclear to properly implement.
